version: '3.0'

services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 1s
      timeout: 1s
      retries: 5
  migrate:
    image: migrate/migrate
    volumes:
      - ./migration:/migration
    entrypoint:
      [
        "migrate",
        "-path",
        "/migration",
        "-database",
        "${DB_DRIVER}://${DB_USERNAME}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=${SSL_MODE}",
      ]
    command: ["up"]
    depends_on:
      db:
        condition: service_healthy